// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLPhanPhoiThuoc.Models.EF;

#nullable disable

namespace QLPhanPhoiThuoc.Migrations.BenhVien
{
    [DbContext(typeof(BenhVienDbContext))]
    partial class BenhVienDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.BenhNhan", b =>
                {
                    b.Property<string>("MaBenhNhan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<decimal?>("CanNang")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("ChieuCao")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LoaiBenhNhan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("NgoaiTru");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NgheNghiep")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NhomMau")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenBenhNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TienSuDiUng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("HoatDong");

                    b.HasKey("MaBenhNhan");

                    b.HasIndex("SoDienThoai")
                        .HasDatabaseName("idx_sdt");

                    b.HasIndex("TenBenhNhan")
                        .HasDatabaseName("idx_tenbn");

                    b.ToTable("BenhNhan", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.CauHinhHeThong", b =>
                {
                    b.Property<string>("MaCauHinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiDuLieu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenCauHinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCauHinh");

                    b.HasIndex("TenCauHinh")
                        .IsUnique()
                        .HasDatabaseName("idx_tencauhinh");

                    b.ToTable("CauHinhHeThong", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.CauHinhVietQR", b =>
                {
                    b.Property<string>("MaCauHinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("APIKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("APISecret")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaNganHang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Template")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("compact2");

                    b.Property<string>("TenNganHang")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("KichHoat");

                    b.Property<string>("WebhookURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaCauHinh");

                    b.ToTable("CauHinh_VietQR", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.ChanDoan", b =>
                {
                    b.Property<string>("MaChanDoan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChanDoanSoBo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KetLuan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaBenhNhan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaICD10")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayChanDoan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenBenh")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TrieuChung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChanDoan");

                    b.HasIndex("MaBenhNhan")
                        .HasDatabaseName("idx_benhnhan");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("NgayChanDoan")
                        .HasDatabaseName("idx_ngaychandoan");

                    b.ToTable("ChanDoan", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.ChiTietDonThuoc", b =>
                {
                    b.Property<string>("MaDonThuoc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(0);

                    b.Property<string>("MaThuoc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(1);

                    b.Property<string>("CachDung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LieuDung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayDung")
                        .HasColumnType("int");

                    b.Property<string>("ThuocMaThuoc")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaDonThuoc", "MaThuoc");

                    b.HasIndex("MaThuoc");

                    b.HasIndex("ThuocMaThuoc");

                    b.ToTable("ChiTietDonThuoc", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.ChiTietPhieuCap", b =>
                {
                    b.Property<string>("MaPhieuCap")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(0);

                    b.Property<string>("MaLo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(1);

                    b.Property<decimal>("DonGiaCap")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("SoLuongCap")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(15,2)")
                        .HasComputedColumnSql("[SoLuongCap] * [DonGiaCap]");

                    b.HasKey("MaPhieuCap", "MaLo");

                    b.HasIndex("MaLo");

                    b.ToTable("ChiTietPhieuCap", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.Property<string>("MaPhieuNhap")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(0);

                    b.Property<string>("MaLo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(1);

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(15,2)")
                        .HasComputedColumnSql("[SoLuongNhap] * [DonGiaNhap]");

                    b.HasKey("MaPhieuNhap", "MaLo");

                    b.HasIndex("MaLo");

                    b.ToTable("ChiTietPhieuNhap", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.DonThuoc", b =>
                {
                    b.Property<string>("MaDonThuoc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChanDoanSoBo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChuBacSi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiDon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaBenhNhan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaChanDoan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayKeDon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ChoXuLy");

                    b.HasKey("MaDonThuoc");

                    b.HasIndex("LoaiDon")
                        .HasDatabaseName("idx_loaidon");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaChanDoan");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("NgayKeDon")
                        .HasDatabaseName("idx_ngaykedon");

                    b.ToTable("DonThuoc", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaBenhNhan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaDonThuoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("NgayTaoHoaDon")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienBHYTChiTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TienBenhNhanCanTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TienDaTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ChuaTra");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaDonThuoc");

                    b.HasIndex("NgayTaoHoaDon")
                        .HasDatabaseName("idx_ngaytaohoadon");

                    b.HasIndex("TrangThaiThanhToan")
                        .HasDatabaseName("idx_trangthai");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.Kho", b =>
                {
                    b.Property<string>("MaKho")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LoaiKho")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("HoatDong");

                    b.HasKey("MaKho");

                    b.ToTable("Kho", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.KhoaPhong", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("HoatDong");

                    b.Property<string>("TruongKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhoa");

                    b.ToTable("KhoaPhong", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.LoThuoc", b =>
                {
                    b.Property<string>("MaLo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("HanSuDung")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaKho")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaThuoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgaySanXuat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoLo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuongCon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ConHang");

                    b.HasKey("MaLo");

                    b.HasIndex("HanSuDung")
                        .HasDatabaseName("idx_hansudung");

                    b.HasIndex("MaKho")
                        .HasDatabaseName("idx_kho");

                    b.HasIndex("MaThuoc")
                        .HasDatabaseName("idx_thuoc");

                    b.HasIndex("MaThuoc", "MaKho", "SoLo")
                        .IsUnique()
                        .HasDatabaseName("uk_thuoc_kho_solo");

                    b.ToTable("LoThuoc", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.NhaCungCap", b =>
                {
                    b.Property<string>("MaNCC")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("HoatDong");

                    b.HasKey("MaNCC");

                    b.HasIndex("TenNCC")
                        .HasDatabaseName("idx_tenncc");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BangCap")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChuyenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DangLamViec");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("ChucVu")
                        .HasDatabaseName("idx_chucvu");

                    b.HasIndex("ChuyenKhoa")
                        .HasDatabaseName("idx_chuyenkhoa");

                    b.HasIndex("MaKhoa");

                    b.HasIndex("TenNhanVien")
                        .HasDatabaseName("idx_tennv");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.PhieuCapPhat", b =>
                {
                    b.Property<string>("MaPhieuCap")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaBenhNhan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaDonThuoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaKho")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NhanVienCap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DangXuLy");

                    b.HasKey("MaPhieuCap");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaDonThuoc")
                        .HasDatabaseName("idx_donthuoc");

                    b.HasIndex("MaKho");

                    b.HasIndex("NgayCap")
                        .HasDatabaseName("idx_ngaycap");

                    b.HasIndex("NhanVienCap");

                    b.ToTable("PhieuCapPhat", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.PhieuNhap", b =>
                {
                    b.Property<string>("MaPhieuNhap")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaKho")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NhanVienNhap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SoHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DangNhap");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaKho");

                    b.HasIndex("MaNCC")
                        .HasDatabaseName("idx_ncc");

                    b.HasIndex("NgayNhap")
                        .HasDatabaseName("idx_ngaynhap");

                    b.HasIndex("NhanVienNhap");

                    b.ToTable("PhieuNhap", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.PhieuThuTien", b =>
                {
                    b.Property<string>("MaPhieuThu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaGiaoDichNganHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("NgayThu")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienThu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SoTienThu")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DaXacNhan");

                    b.HasKey("MaPhieuThu");

                    b.HasIndex("MaHoaDon")
                        .HasDatabaseName("idx_hoadon");

                    b.HasIndex("NgayThu")
                        .HasDatabaseName("idx_ngaythu");

                    b.HasIndex("NhanVienThu");

                    b.ToTable("PhieuThuTien", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("KichHoat");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaNhanVien")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("idx_username");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.TheBHYT", b =>
                {
                    b.Property<string>("MaThe")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi5Nam")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MaBenhNhan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("MucHuong")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NoiDangKyKCB")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SoTheBHYT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ConHan");

                    b.HasKey("MaThe");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("NgayHetHan")
                        .HasDatabaseName("idx_hethan");

                    b.HasIndex("SoTheBHYT")
                        .IsUnique()
                        .HasDatabaseName("idx_sothe");

                    b.ToTable("TheBHYT", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.ThongBao", b =>
                {
                    b.Property<string>("MaThongBao")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("DaDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("DoUuTien")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Binh");

                    b.Property<string>("LoaiThongBao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NguoiNhan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaThongBao");

                    b.HasIndex("DaDoc")
                        .HasDatabaseName("idx_dadoc");

                    b.HasIndex("DoUuTien")
                        .HasDatabaseName("idx_uutien");

                    b.HasIndex("NgayTao")
                        .HasDatabaseName("idx_ngaytao");

                    b.HasIndex("NguoiNhan");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.Thuoc", b =>
                {
                    b.Property<string>("MaThuoc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DangBaoChe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DuongDung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("GiaNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("GiaXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("HamLuong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoatChat")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LaThuocBHYT")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("No");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NhaSanXuat")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NhomThuoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TonKhoToiThieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("KichHoat");

                    b.Property<decimal>("TyLeBHYTChiTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("MaThuoc");

                    b.HasIndex("HoatChat")
                        .HasDatabaseName("idx_hoatchat");

                    b.HasIndex("LaThuocBHYT")
                        .HasDatabaseName("idx_bhyt");

                    b.HasIndex("NhomThuoc")
                        .HasDatabaseName("idx_nhomthuoc");

                    b.HasIndex("TenThuoc")
                        .HasDatabaseName("idx_tenthuoc");

                    b.ToTable("Thuoc", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.VietQRGiaoDich", b =>
                {
                    b.Property<string>("MaQR")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DuLieuWebhook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaGiaoDichNganHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungChuyenKhoan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QRCodeBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SoTienNhan")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("SoTienYeuCau")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ChoThanhToan");

                    b.HasKey("MaQR");

                    b.HasIndex("MaHoaDon")
                        .HasDatabaseName("idx_hoadon");

                    b.HasIndex("NoiDungChuyenKhoan")
                        .HasDatabaseName("idx_noidung");

                    b.ToTable("VietQR_GiaoDich", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.ChanDoan", b =>
                {
                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.BenhNhan", "BenhNhan")
                        .WithMany("ChanDoans")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BenhNhan");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.ChiTietDonThuoc", b =>
                {
                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.DonThuoc", "DonThuoc")
                        .WithMany("ChiTietDonThuocs")
                        .HasForeignKey("MaDonThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.Thuoc", "Thuoc")
                        .WithMany()
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.Thuoc", null)
                        .WithMany("ChiTietDonThuocs")
                        .HasForeignKey("ThuocMaThuoc");

                    b.Navigation("DonThuoc");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.ChiTietPhieuCap", b =>
                {
                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.LoThuoc", "LoThuoc")
                        .WithMany()
                        .HasForeignKey("MaLo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.PhieuCapPhat", "PhieuCapPhat")
                        .WithMany("ChiTietPhieuCaps")
                        .HasForeignKey("MaPhieuCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoThuoc");

                    b.Navigation("PhieuCapPhat");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.LoThuoc", "LoThuoc")
                        .WithMany()
                        .HasForeignKey("MaLo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoThuoc");

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.DonThuoc", b =>
                {
                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.BenhNhan", "BenhNhan")
                        .WithMany("DonThuocs")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.ChanDoan", "ChanDoan")
                        .WithMany("DonThuocs")
                        .HasForeignKey("MaChanDoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BenhNhan");

                    b.Navigation("ChanDoan");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.HoaDon", b =>
                {
                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.BenhNhan", "BenhNhan")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.DonThuoc", "DonThuoc")
                        .WithMany()
                        .HasForeignKey("MaDonThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BenhNhan");

                    b.Navigation("DonThuoc");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.LoThuoc", b =>
                {
                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.Kho", "Kho")
                        .WithMany("LoThuocs")
                        .HasForeignKey("MaKho")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.Thuoc", "Thuoc")
                        .WithMany("LoThuocs")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kho");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.NhanVien", b =>
                {
                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.KhoaPhong", "KhoaPhong")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhoaPhong");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.PhieuCapPhat", b =>
                {
                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.BenhNhan", "BenhNhan")
                        .WithMany()
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.DonThuoc", "DonThuoc")
                        .WithMany()
                        .HasForeignKey("MaDonThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("MaKho")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienCap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BenhNhan");

                    b.Navigation("DonThuoc");

                    b.Navigation("Kho");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.PhieuNhap", b =>
                {
                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.Kho", "Kho")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaKho")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienNhap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kho");

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.PhieuThuTien", b =>
                {
                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.HoaDon", "HoaDon")
                        .WithMany("PhieuThuTiens")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienThu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.TaiKhoan", b =>
                {
                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.NhanVien", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("QLPhanPhoiThuoc.Models.Entities.TaiKhoan", "MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.TheBHYT", b =>
                {
                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.BenhNhan", "BenhNhan")
                        .WithMany("TheBHYTs")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.ThongBao", b =>
                {
                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NguoiNhan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.VietQRGiaoDich", b =>
                {
                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.BenhNhan", b =>
                {
                    b.Navigation("ChanDoans");

                    b.Navigation("DonThuocs");

                    b.Navigation("HoaDons");

                    b.Navigation("TheBHYTs");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.ChanDoan", b =>
                {
                    b.Navigation("DonThuocs");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.DonThuoc", b =>
                {
                    b.Navigation("ChiTietDonThuocs");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.HoaDon", b =>
                {
                    b.Navigation("PhieuThuTiens");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.Kho", b =>
                {
                    b.Navigation("LoThuocs");

                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.KhoaPhong", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.NhaCungCap", b =>
                {
                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.NhanVien", b =>
                {
                    b.Navigation("TaiKhoan")
                        .IsRequired();
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.PhieuCapPhat", b =>
                {
                    b.Navigation("ChiTietPhieuCaps");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.Thuoc", b =>
                {
                    b.Navigation("ChiTietDonThuocs");

                    b.Navigation("LoThuocs");
                });
#pragma warning restore 612, 618
        }
    }
}
