// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLPhanPhoiThuoc.Models.EF;

#nullable disable

namespace QLPhanPhoiThuoc.Migrations.VNeID
{
    [DbContext(typeof(VNeIDDbContext))]
    [Migration("20260203022458_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.VNeID.CauHinhTichHop", b =>
                {
                    b.Property<string>("MaCauHinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("APIKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("APISecret")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IPWhitelist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Danh sách IP được phép, cách nhau bởi dấu phẩy");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("SoLanTraCuuToiDa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1000)
                        .HasComment("Giới hạn số lần tra cứu/ngày");

                    b.Property<string>("TenHeThong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("KichHoat");

                    b.HasKey("MaCauHinh");

                    b.HasIndex("APIKey")
                        .IsUnique()
                        .HasDatabaseName("idx_apikey");

                    b.ToTable("CauHinhTichHop", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.VNeID.CongDan", b =>
                {
                    b.Property<string>("SoDinhDanh")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasComment("Số CCCD/CMND");

                    b.Property<string>("AnhChanDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Base64 hoặc URL ảnh");

                    b.Property<string>("DanToc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChiHienTai")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NoiCap")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NoiThuongTru")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QuocTich")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Việt Nam");

                    b.Property<string>("TonGiao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("HoatDong");

                    b.HasKey("SoDinhDanh");

                    b.HasIndex("HoTen")
                        .HasDatabaseName("idx_hoten");

                    b.HasIndex("NgaySinh")
                        .HasDatabaseName("idx_ngaysinh");

                    b.ToTable("CongDan", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.VNeID.LichSuTraCuu", b =>
                {
                    b.Property<string>("MaTraCuu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DuLieuTraVe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("JSON response");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HeThongTraCuu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Tên hệ thống yêu cầu");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoaiTraCuu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayGioTraCuu")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDinhDanh")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int?>("ThoiGianXuLy")
                        .HasColumnType("int")
                        .HasComment("Milliseconds");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaTraCuu");

                    b.HasIndex("HeThongTraCuu")
                        .HasDatabaseName("idx_hethong");

                    b.HasIndex("NgayGioTraCuu")
                        .HasDatabaseName("idx_ngaygio");

                    b.HasIndex("SoDinhDanh")
                        .HasDatabaseName("idx_sodinhhanh");

                    b.ToTable("LichSuTraCuu", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.VNeID.TheBHYTMock", b =>
                {
                    b.Property<string>("MaThe")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi5Nam")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Nơi cư trú 5 năm liên tục");

                    b.Property<string>("MaKhuVuc")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("K1, K2, K3");

                    b.Property<string>("MaNoiDKKCB")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Mã BV đăng ký");

                    b.Property<decimal>("MucHuong")
                        .HasColumnType("decimal(5,2)")
                        .HasComment("80, 95, 100");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NoiDKKCB")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nơi đăng ký khám chữa bệnh ban đầu");

                    b.Property<string>("SoDinhDanh")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("SoTheBHYT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Mã thẻ BHYT 15 ký tự");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ConHan");

                    b.HasKey("MaThe");

                    b.HasIndex("NgayHetHan")
                        .HasDatabaseName("idx_hethan");

                    b.HasIndex("SoDinhDanh")
                        .HasDatabaseName("idx_sodinhhanh");

                    b.HasIndex("SoTheBHYT")
                        .IsUnique()
                        .HasDatabaseName("idx_sothe");

                    b.ToTable("TheBHYT_Mock", (string)null);
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.VNeID.LichSuTraCuu", b =>
                {
                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.VNeID.CongDan", "CongDan")
                        .WithMany("LichSuTraCuus")
                        .HasForeignKey("SoDinhDanh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CongDan");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.VNeID.TheBHYTMock", b =>
                {
                    b.HasOne("QLPhanPhoiThuoc.Models.Entities.VNeID.CongDan", "CongDan")
                        .WithMany("TheBHYTMocks")
                        .HasForeignKey("SoDinhDanh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CongDan");
                });

            modelBuilder.Entity("QLPhanPhoiThuoc.Models.Entities.VNeID.CongDan", b =>
                {
                    b.Navigation("LichSuTraCuus");

                    b.Navigation("TheBHYTMocks");
                });
#pragma warning restore 612, 618
        }
    }
}
